name: Nix flake check (reusable)

on:
  workflow_call:
    inputs:
      platforms:
        description: "JSON array of runner OS values"
        type: string
        default: '["ubuntu-latest"]'

permissions:
  contents: read

jobs:
  flake-check:
    name: nix flake check (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(inputs.platforms) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: DeterminateSystems/determinate-nix-action@73327eb48f028efaaf5013656ba216ca3cdeca7b # v3
      - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
        with:
          use-flakehub: false
      - uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12
      - run: nix flake check
